# Numpy 
넘파이는 다차원 배열을 다루는 데 유용한 파이썬 라이브러리입니다. 자세한 튜토리얼은 아래를 참고하시기 바랍니다.
1. The SciPy community: https://numpy.org/devdocs/user/quickstart.html 
2. 텐서 플로우 블로그: https://tensorflow.blog/핸즈온-머신러닝-1장-2장/넘파이-튜토리얼

## 기본 개념

예를 들어 다음과 같은 행렬 계산을 넘파이로 계산해보겠습니다.

$$
\mathbf{}
\begin{bmatrix}
1 & 1 \\ 
0 & 2 \\  
\end{bmatrix}
\begin{bmatrix} 
1 \\ 2
\end{bmatrix}
=
\begin{bmatrix} 
3 \\ 4
\end{bmatrix}
$$

우선 A와 x에 해당하는 넘파이 배열을 생성해준 뒤,

In [1]:
import numpy as np

A = np.array([[1, 1], [0, 2]])
x = np.array([1, 2])

```np.dot()``` 메서드를 이용하면 됩니다.

In [2]:
np.dot(A, x)

array([3, 4])

파이썬의 리스트 자료형으로는 이처럼 계산할 수 없습니다. 하지만 넘파이 배열을 이용하면 다차원 배열을 쉽게 조작할 수 있습니다. 위에서는 2x2 행렬을 예로 들었지만, 더 큰 차원의 배열도 다룰 수 있습니다. 예를 들어보겠습니다.

In [3]:
A = np.array([[[1, 1], [0, 2], [0, 2]], 
              [[1, 1], [0, 2], [0, 2]]])
A

array([[[1, 1],
        [0, 2],
        [0, 2]],

       [[1, 1],
        [0, 2],
        [0, 2]]])

 ```.shape```을 통해 배열의 크기를 확인할 수 있습니다.

In [4]:
A.shape

(2, 3, 2)

이때 (2, 3, 2)에서 각각의 차원을 축(axis)라고 합니다. ```A```의 첫 번째 축의 크기는 2, 두 번째 축의 크기는 3, 세 번째 축의 크기는 2입니다. 축의 개수를 랭크(rank)라고 하는데, 랭크를 확인하고 싶을 때는 ```ndim```을 이용합니다.

In [5]:
A.ndim

3

## 배열 생성하기

### np.array()
넘파이 배열은 ```np.array()``` 안에 리스트(또는 튜플)을 넣는 방식으로 생성할 수 있습니다.

In [6]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)
print(arr.shape)

[1 2 3]
(3,)


```np.array()``` 안에 리스트의 리스트 형식으로 넣어주면 행렬이 됩니다.

In [7]:
arr = np.array([[1, 2, 3], 
                [2, 3, 4]])
print(arr)
print(arr.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


### np.ones(), np.zeros()
```np.ones()```는 원소가 1인 넘파이 배열을 생성합니다. 예를 들어 ```np.ones((1, 2))```라고 입력하면 1x2 크기의 배열을 생성합니다.

In [8]:
np.ones((1, 2))

array([[1., 1.]])

반면 ```np.zeros()```는 원소가 1인 넘파이 배열을 생성합니다.

In [9]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.arange()

```np.arange()```는 ```range()```와 사용법이 비슷합니다. ```np.arange(12)```라고 입력하면 원소가 0부터 11까지인 배열을 생성합니다.

In [10]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

### np.random.rand(), np.random.randn()
```np.random```에는 난수 생성을 위한 기능들이 있습니다. 2개만 소개하겠습니다.

```np.random.rand()```은 범위가 [0, 1] 사이인 수 중에서 임의의 값을 추출해, 지정된 크기의 배열을 생성합니다..

In [12]:
# 크기가 (3, 2)인 넘파이 배열 생성.
np.random.rand(3, 2)

array([[0.62121009, 0.71390923],
       [0.13754771, 0.47620546],
       [0.79103916, 0.22812876]])

반면 ```np.random.randn()```은 표준정규분포(평균이 0이고 표준편차가 1인 정규분포)에서 값을 추출합니다.

In [13]:
# 크기가 (3, 2)인 넘파이 배열 생성.
np.random.randn(3, 2)

array([[ 0.58033915,  0.56441547],
       [-0.26850709, -0.6292239 ],
       [ 0.12954459,  0.77886593]])

### np.linspace()
```np.linspace(start, stop, num=50)```은 start와 stop 사이를 num만큼 일정한 간격으로 나누어서 배열을 생성합니다. 예를 들어```np.linspace(1, 10, 10)```이라고 입력하면 1부터 10 사이를 일정한 구간으로 나누어 원소가 10개인 배열을 생성합니다.

In [14]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## 배열 크기 조작하기

### reshape()
```reshape()```를 이용하면 배열의 크기를 바꿀 수 있습니다.

In [15]:
x = np.arange(12)
print('크기 변경 전: \n', x)
x = x.reshape(3, 4)
print('크기 변경 후: \n', x)

크기 변경 전: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
크기 변경 후: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### ravel()
```ravel()```을 사용하면 다차원 배열을 랭크 1인 배열로 바꾸어줍니다.

In [16]:
A = np.arange(12).reshape(3, 4)
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### .T
```.T```를 이용해 행렬을 전치할 수 있습니다.

In [17]:
A = np.arange(12).reshape(3, 4)
A.T.shape

(4, 3)

## 인덱싱
예를 들어, 다음과 같은 배열 ```A```가 있을 때, ```A[1, 2]```라고 입력하면, 1행 2열의 원소를 참조할 수 있습니다.

In [18]:
A = np.arange(12).reshape(3, 4)
print(A)
print(A[1, 2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6


리스트 슬라이싱을 하는 방식과 마찬가지로, ```A[1:, :2]```라고 입력하면 [1행 이후, 2열 이전]을 배열로 가져옵니다.

In [19]:
A[1:, :2]

array([[4, 5],
       [8, 9]])

또한 다음과 같이 원하는 행만 취해서 가져올 수도 있습니다.

In [20]:
# 0, 2번 행만 가져오기
A[[0,2], :]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

## 연산
평균, 분산, 표준편차, 최댓값 등 생각할 수 있는 기본적인 연산은 모두 제공됩니다. 필요한 기능이 있으면 그때 구글에 검색해서 사용해보세요.

In [21]:
# 평균 구하기 
A = np.arange(12).reshape(3, 4)
A.mean()

5.5

In [22]:
# 표준편차 구하기
A.std()

3.452052529534663

In [23]:
# 최댓값 구하기
A.max()

11

In [24]:
# 최댓값을 가지는 원소의 인덱스 가져오기
A.argmax()

11

같은 방식의 연산을 ```np.mean()```, ```np.std()``` 등으로도 할 수 있습니다.

In [25]:
np.mean(A)

5.5

연산을 할 때 어떤 축을 기준으로 계산할 것인지 지정할 수 있습니다. ```axis=0```이면 같은 열 안에서 연산을 하고, ```axis=1```이면 행별로 연산을 합니다.

In [26]:
np.mean(A, axis=1)

array([1.5, 5.5, 9.5])

### 원소별 연산
예를 들어 크기가 (3, 3)인 두 배열을 더하면, 같은 위치에 있는 원소끼리 덧셈이 수행됩니다. 곱셈도 마찬가지입니다.

In [27]:
arr = np.arange(6).reshape(3, 2)
arr + arr

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

universial function은 각각의 원소에 연산이 적용되는 함수입니다. 예를 들어 배열에 ```np.sqrt()```를 적용하면, 각각의 원소의 제곱근을 계산해서 같은 크기의 배열로 반환해줍니다.

In [28]:
# 제곱근 계산
np.sqrt(arr)

array([[0.        , 1.        ],
       [1.41421356, 1.73205081],
       [2.        , 2.23606798]])

In [29]:
# 자연상수를 밑으로 가지는 지수 계산
np.exp(arr)

array([[  1.        ,   2.71828183],
       [  7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 ]])

### 브로드 캐스팅
배열 간 연산을 수행할 때, 크기가 서로 다를 수도 있습니다. 예를 들어 크기가 (3, 2)인 배열과 (3, 1)인 배열끼리 연산을 하면 어떻게 될까요? 답은 (3, 1) 배열의 크기를 (3, 2)으로 자동으로 확장시킨 후에 연산을 한다는 것입니다. 이를 브로드 캐스팅이라고 합니다.

In [30]:
arr1 = np.arange(6).reshape(3, 2)
arr2 = np.ones((3, 1)).reshape(3, 1)
arr1 + arr2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

배열과 단일한 숫자 하나를 연산할 때도 마찬가지입니다.

In [31]:
arr1 + 3

array([[3, 4],
       [5, 6],
       [7, 8]])